### ISSUE TITLE
Unknown column 't1.effective_from_date_time' in 'field list'

### ISSUE THREAD

**Issue by rfgunion** [AdvancedPhotonSource/ComponentDB#611]
I installed a fresh copy of CDB in a docker container following the instructions on the README.  This involved creating a completely new database from the cdb_create_db.sh script.  After creating my first location the UI crashes and the server.log has an error message like the below.  The property_value table does indeed not have a "effective_from_date_time" column.  Is this a mismatch between the cdb_create_db.sh script and the current schema?

Call: SELECT t1.ID, t1.DESCRIPTION, t1.display_value, t1.effective_from_date_time, t1.effective_to_date_time, t1.entered_on_date_time, t1.is_dynamic, t1.is_user_writeable, t1.TAG, t1.target_value, t1.UNITS, t1.VALUE, t1.entered_by_user_id, t1.property_type_id FROM item_element_property t0, property_value t1 WHERE ((t0.item_element_id = ?) AND (t1.ID = t0.property_value_id))
        bind => [1 parameter bound]
Query: ReadAllQuery(name="propertyValueList" referenceClass=PropertyValue sql="SELECT t1.ID, t1.DESCRIPTION, t1.display_value, t1.effective_from_date_time, t1.effective_to_date_time, t1.entered_on_date_time, t1.is_dynamic, t1.is_user_writeable, t1.TAG, t1.target_value, t1.UNITS, t1.VALUE, t1.entered_by_user_id, t1.property_type_id FROM item_element_property t0, property_value t1 WHERE ((t0.item_element_id = ?) AND (t1.ID = t0.property_value_id))")
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:691)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2096)
        at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:603)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:263)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:275)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:261)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:332)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:728)
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2773)
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2726)
        at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:584)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1224)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:914)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1183)
        at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:485)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1271)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2981)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1895)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1877)
        at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:135)
        at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:122)
        at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:97)
        at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiateImpl(UnitOfWorkValueHolder.java:175)
        at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiate(UnitOfWorkValueHolder.java:236)
        at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:97)
        at org.eclipse.persistence.indirection.IndirectList.buildDelegate(IndirectList.java:275)
        at org.eclipse.persistence.indirection.IndirectList.getDelegate(IndirectList.java:458)
        at org.eclipse.persistence.indirection.IndirectList$1.<init>(IndirectList.java:602)
        at org.eclipse.persistence.indirection.IndirectList.listIterator(IndirectList.java:601)
        at org.eclipse.persistence.indirection.IndirectList.iterator(IndirectList.java:560)
        at gov.anl.aps.cdb.portal.controllers.ItemController.getPropertyValueListWithHandler(ItemController.java:2181)
        at gov.anl.aps.cdb.portal.controllers.ItemController.getPropertyValueListWithHandlerForImages(ItemController.java:2175)
        at gov.anl.aps.cdb.portal.controllers.ItemController.getPrimaryImagePropertyValueForItem(ItemController.java:2155)
        at gov.anl.aps.cdb.portal.controllers.ItemController.loadItemPrimaryImageValueForItem(ItemController.java:2144)
        at gov.anl.aps.cdb.portal.controllers.ItemController.getPrimaryImageValueForItem(ItemController.java:2129)
        at gov.anl.aps.cdb.portal.controllers.ItemController.itemHasPrimaryImage(ItemController.java:2104)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at javax.el.ELUtil.invokeMethod(ELUtil.java:263)
        ... 91 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't1.effective_from_date_time' in 'field list'
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2503)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2794)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2322)
        at com.sun.gjc.spi.jdbc40.PreparedStatementWrapper40.executeQuery(PreparedStatementWrapper40.java:643)
        at jdk.internal.reflect.GeneratedMethodAccessor487.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40$1.invoke(ProfiledConnectionWrapper40.java:437)
        at com.sun.proxy.$Proxy542.executeQuery(Unknown Source)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1015)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:651)
        ... 132 more
]]

**Comment by rfgunion** [comment]
Ah never mind, somehow I got an old database schema installed with my new docker instance.  After going back through the normal install process, all is well.
